// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SplamyWeb.Db;

namespace SplamyWeb.Migrations
{
    [DbContext(typeof(SplamyContext))]
    [Migration("20210716172722_UpdatedJbmFormat")]
    partial class UpdatedJbmFormat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("SplamyWeb.Components.CachedDayStats", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("PlaybackTime")
                        .HasColumnType("interval");

                    b.Property<long>("RunningBots")
                        .HasColumnType("bigint");

                    b.Property<long>("RunningInstances")
                        .HasColumnType("bigint");
                });

            modelBuilder.Entity("SplamyWeb.Components.PlaytimeDto", b =>
                {
                    b.Property<TimeSpan?>("Playtime")
                        .HasColumnType("interval");
                });

            modelBuilder.Entity("SplamyWeb.Db.LanguageEntry", b =>
                {
                    b.Property<string>("Project")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Project", "Language");

                    b.ToTable("nightly_lang");
                });

            modelBuilder.Entity("SplamyWeb.Db.LoginData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("SplamyWeb.Db.NightlyBranch", b =>
                {
                    b.Property<string>("Project")
                        .HasColumnType("text");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Active")
                        .HasColumnType("text");

                    b.HasKey("Project", "Branch");

                    b.ToTable("nightly_branch");
                });

            modelBuilder.Entity("SplamyWeb.Db.NightlyBuild", b =>
                {
                    b.Property<string>("Project")
                        .HasColumnType("text");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Commit")
                        .HasColumnType("text");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ZipContent")
                        .HasColumnType("boolean");

                    b.HasKey("Project", "Branch", "Commit");

                    b.ToTable("nightly_build");
                });

            modelBuilder.Entity("SplamyWeb.Db.NightlyProject", b =>
                {
                    b.Property<string>("Project")
                        .HasColumnType("text");

                    b.Property<string>("CommitUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Project");

                    b.ToTable("nightly_project");
                });

            modelBuilder.Entity("SplamyWeb.Db.RamsesMapDto", b =>
                {
                    b.Property<long>("RamsesId")
                        .HasColumnType("bigint");

                    b.Property<int>("Characteristic")
                        .HasColumnType("integer");

                    b.Property<byte>("IndexDifficulty")
                        .HasColumnType("smallint");

                    b.Property<byte>("Difficulty")
                        .HasColumnType("smallint");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<byte[]>("RatingDetail")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("RamsesId", "Characteristic", "IndexDifficulty");

                    b.ToTable("ramses_map");
                });

            modelBuilder.Entity("SplamyWeb.Db.RamsesSongDto", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RawMap")
                        .HasColumnType("bytea");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ramses_song");
                });

            modelBuilder.Entity("SplamyWeb.Db.StoreEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("kvp_store");
                });

            modelBuilder.Entity("SplamyWeb.Db.TabStatsFactoryDto", b =>
                {
                    b.Property<long>("TabStatsId")
                        .HasColumnType("bigint");

                    b.Property<string>("FactoryName")
                        .HasColumnType("text");

                    b.Property<long>("PlayFromUser")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayRequests")
                        .HasColumnType("bigint");

                    b.Property<long>("PlaySucessful")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("Playtime")
                        .HasColumnType("interval");

                    b.Property<long>("SearchRequests")
                        .HasColumnType("bigint");

                    b.HasKey("TabStatsId", "FactoryName");

                    b.ToTable("tabstats_factory");
                });

            modelBuilder.Entity("SplamyWeb.Db.TabStatsPingDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BotVersion")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("BotsRuntime")
                        .HasColumnType("interval");

                    b.Property<long>("CommandCalls")
                        .HasColumnType("bigint");

                    b.Property<long>("CommandFromApi")
                        .HasColumnType("bigint");

                    b.Property<long>("CommandFromUser")
                        .HasColumnType("bigint");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<long>("RunningBots")
                        .HasColumnType("bigint");

                    b.Property<string>("Runtime")
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("TotalUptime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("tabstats_entry");
                });

            modelBuilder.Entity("SplamyWeb.Db.LanguageEntry", b =>
                {
                    b.HasOne("SplamyWeb.Db.NightlyProject", "NightlyProject")
                        .WithMany("Languages")
                        .HasForeignKey("Project")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NightlyProject");
                });

            modelBuilder.Entity("SplamyWeb.Db.NightlyBranch", b =>
                {
                    b.HasOne("SplamyWeb.Db.NightlyProject", "NightlyProject")
                        .WithMany("Branches")
                        .HasForeignKey("Project")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NightlyProject");
                });

            modelBuilder.Entity("SplamyWeb.Db.NightlyBuild", b =>
                {
                    b.HasOne("SplamyWeb.Db.NightlyBranch", "NightlyBranch")
                        .WithMany("Builds")
                        .HasForeignKey("Project", "Branch")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NightlyBranch");
                });

            modelBuilder.Entity("SplamyWeb.Db.RamsesMapDto", b =>
                {
                    b.HasOne("SplamyWeb.Db.RamsesSongDto", "RamsesEntry")
                        .WithMany("Maps")
                        .HasForeignKey("RamsesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RamsesEntry");
                });

            modelBuilder.Entity("SplamyWeb.Db.TabStatsFactoryDto", b =>
                {
                    b.HasOne("SplamyWeb.Db.TabStatsPingDto", "TabStatsEntry")
                        .WithMany("SongStats")
                        .HasForeignKey("TabStatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabStatsEntry");
                });

            modelBuilder.Entity("SplamyWeb.Db.NightlyBranch", b =>
                {
                    b.Navigation("Builds");
                });

            modelBuilder.Entity("SplamyWeb.Db.NightlyProject", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Languages");
                });

            modelBuilder.Entity("SplamyWeb.Db.RamsesSongDto", b =>
                {
                    b.Navigation("Maps");
                });

            modelBuilder.Entity("SplamyWeb.Db.TabStatsPingDto", b =>
                {
                    b.Navigation("SongStats");
                });
#pragma warning restore 612, 618
        }
    }
}
