// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SplamyWeb.Db;

namespace SplamyWeb.Migrations
{
    [DbContext(typeof(SplamyContext))]
    partial class SplamyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SplamyWeb.Db.RamsesEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ramses_entry");
                });

            modelBuilder.Entity("SplamyWeb.Db.RamsesMap", b =>
                {
                    b.Property<long>("RamsesId")
                        .HasColumnType("bigint");

                    b.Property<string>("Characteristic")
                        .HasColumnType("text");

                    b.Property<byte>("Difficulty")
                        .HasColumnType("smallint");

                    b.Property<float>("AvgDifficulty")
                        .HasColumnType("real");

                    b.Property<float[]>("Graph")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<float>("MaxDifficulty")
                        .HasColumnType("real");

                    b.HasKey("RamsesId", "Characteristic", "Difficulty");

                    b.ToTable("ramses_map");
                });

            modelBuilder.Entity("SplamyWeb.Db.RamsesMap", b =>
                {
                    b.HasOne("SplamyWeb.Db.RamsesEntry", "RamsesEntry")
                        .WithMany("Maps")
                        .HasForeignKey("RamsesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
