# For more info on HTTP files go to https://aka.ms/vs/httpfile
#@Auth=Basic c3BsYW15OnRlc3Rwdw====

### System db metadata

GET {{HostAddress}}/api/ramses/system

###

GET {{HostAddress}}/api/ramses/m/2B13F

###

GET {{HostAddress}}/api/ramses/info/i241407/map

###

POST {{HostAddress}}/api/ramses/q/json
Content-Type: application/json
Authorization: {{Auth}}

{
	"_songName": "Halloween Spooky Mash Up"
}

###

POST {{HostAddress}}/api/ramses/q/logic
Content-Type: application/json
Authorization: {{Auth}}


{"==" : [ { "var" : "_songName" }, "Halloween Spooky Mash Up" ]}

### RSS Proxy Rhythm Quest

GET {{HostAddress}}/api/rssproxy/rhythm_quest
